# Generated by Django 5.2.7 on 2025-11-11 12:47

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_admin_user_is_staff_remove_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.id_back_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.id_front_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be 14 digits.', regex='^\\d{14}$')]),
        ),
    ]
